### ISSUE TITLE
Links in Nav Bar

### ISSUE THREAD

**Issue by colegregory** [YACS-RCOS/yacs-admin#123]
In the nav bar, links are limited to the text only. The cursor changes to pointer, though, for the entire surrounding area. This might be a little unintuitive for users.
A fix could be either making the entire rectangle a link, or only changing the cursor to pointer when hovering over text.

**Comment by kburk1997** [comment]
Should be fixed now! I actually took an approach different than what you suggested: I had to change the CSS around quite a bit so that the `<a>` tag would span the whole width of the rectangle. This seems to work when the `display` attribute is changed to `inline-block`.
