### ISSUE TITLE
Add label to instructor field in section detail component

### ISSUE THREAD

**Issue by kburk1997** [YACS-RCOS/yacs-admin#192]
Currently, all form fields in the section detail component have labels except for the instructor field. Without a label, this form field is not read properly by screen readers.

**Comment by Malorn44** [comment]
Was this already resolved? I know the issue is shown as open but it looks like instructor does have a label.
![screenshot from 2018-10-02 13-00-00](https://user-images.githubusercontent.com/11843425/46364201-1f988d80-c643-11e8-8080-cf6a80dab881.png)
