### ISSUE TITLE
Upgrade to Rails 5 or 4.2.8 and enfore Ruby 2.4.0

### ISSUE THREAD

**Issue by Bad-Science** [YACS-RCOS/yacs-admin#35]
Rails 4.2.6 has some known vulnerabilities. Rails 4.2 is still supported but will probably reach end of life in the nearish future. It would be easier to upgrade to rails 5 sooner than later but its not a huge priority. Please do enforce ruby 2.4.0 in the Gemfile though.

**Comment by kburk1997** [comment]
Ok, haven't thought about it at all whoops

**Comment by Bad-Science** [comment]
No worries! Not really an issue until we are in production

**Comment by kburk1997** [comment]
Currently in progress, seems to be working ok. Updated now to prevent new members from having to downgrade Rails.
