### ISSUE TITLE
Change title to 'YACS Admin'

### ISSUE THREAD

**Issue by kburk1997** [YACS-RCOS/yacs-admin#97]
The title in the browser is still the default title, which is 'YacsAdminAngular'. Change this to 'YACS Admin'. In the end-to-end tests, add a test to verify this title.

**Comment by colegregory** [comment]
I fixed the page title. Maybe we could use the router module to set dynamic page titles in the future. So when viewing Schools the title might add '- School' or something.

**Comment by kburk1997** [comment]
All done. That's a good suggestion too, we could create another issue
